name: NurQA Quality Gate CI

# Запускать тесты при каждом пуше или создании Pull Request
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Берем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Устанавливаем зависимости из твоего requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запускаем тесты
      - name: Run tests
        run: |
          pytest